const placeholder = "../assets/brand_logo_240x240.jpg";

export const items = [
  {
    id: 1,
    name: "Chocolate Delight",
    description:
      "Rich chocolate cake topped with chocolate ganache and berries.",
    price: 29.99,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
    inStock: true,
  },
  {
    id: 2,
    name: "Vanilla Dream",
    description: "Light and fluffy vanilla cake with buttercream frosting.",
    price: 24.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 3,
    name: "Red Velvet Cake",
    description: "Classic red velvet cake with cream cheese frosting.",
    price: 27.99,
    imageUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348",
    inStock: false,
  },
  {
    id: 4,
    name: "Lemon Raspberry",
    description:
      "Zesty lemon cake with raspberry filling and cream cheese frosting.",
    price: 32.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 5,
    name: "Carrot Cake",
    description: "Moist carrot cake with walnuts and cream cheese frosting.",
    price: 28.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 6,
    name: "Strawberry Shortcake",
    description:
      "Layers of sponge cake with fresh strawberries and whipped cream.",
    price: 31.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 7,
    name: "Coconut Paradise",
    description: "Coconut cake with layers of creamy coconut frosting.",
    price: 26.99,
    imageUrl: placeholder,
    inStock: false,
  },
  {
    id: 8,
    name: "Almond Cake",
    description: "Delicate almond-flavored cake with toasted almonds on top.",
    price: 33.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 9,
    name: "Coffee Walnut Cake",
    description: "Rich coffee cake with crunchy walnuts and a coffee glaze.",
    price: 29.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 10,
    name: "Black Forest",
    description: "Chocolate cake with cherries and whipped cream.",
    price: 34.99,
    imageUrl: placeholder,
    inStock: false,
  },
  {
    id: 11,
    name: "Tiramisu",
    description: "Italian classic cake with coffee, mascarpone, and cocoa.",
    price: 35.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 12,
    name: "Matcha Green Tea Cake",
    description: "Japanese-inspired matcha cake with a light cream filling.",
    price: 31.99,
    imageUrl: "https://images.unsplash.com/photo-1560457079-9a6532ccb118",
    inStock: true,
  },
  {
    id: 13,
    name: "Orange Creamsicle Cake",
    description: "Bright orange cake with a creamy orange filling.",
    price: 30.99,
    imageUrl: "https://images.unsplash.com/photo-1562059390-a761a084768e",
    inStock: false,
  },
  {
    id: 14,
    name: "Peanut Butter Chocolate",
    description:
      "Chocolate and peanut butter layers with a smooth peanut butter frosting.",
    price: 29.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 15,
    name: "Funfetti Cake",
    description:
      "Vanilla cake filled with rainbow sprinkles and topped with confetti icing.",
    price: 27.99,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
    inStock: true,
  },
  {
    id: 16,
    name: "Banana Nut Cake",
    description: "Moist banana cake with walnuts and cream cheese frosting.",
    price: 26.99,
    imageUrl: placeholder,
    inStock: false,
  },
  {
    id: 17,
    name: "Mango Mousse Cake",
    description:
      "Light and refreshing mango mousse cake with tropical flavors.",
    price: 32.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 18,
    name: "Pineapple Upside Down Cake",
    description: "Caramelized pineapple slices on a buttery cake.",
    price: 28.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 19,
    name: "Blueberry Cheesecake",
    description: "Creamy cheesecake with a blueberry topping.",
    price: 33.99,
    imageUrl: placeholder,
    inStock: true,
  },
  {
    id: 20,
    name: "Triple Chocolate Cake",
    description: "Layers of dark, milk, and white chocolate cake.",
    price: 35.99,
    imageUrl: placeholder,
    inStock: true,
  },
];
