const dummyCakes = [
  {
    id: 1,
    imageSrc: "/assets/images/cake1.jpg",
    imageAlt: "Chocolate Cake",
    title: "Chocolate Delight",
    price: "25.00",
    description: "A rich chocolate cake with creamy frosting.",
    badgeLabel: "Best Seller",
  },
  {
    id: 2,
    imageSrc: "/assets/images/cake2.jpg",
    imageAlt: "Vanilla Cake",
    title: "Vanilla Dream",
    price: "20.00",
    description: "A light vanilla cake with almond notes.",
  },
  {
    id: 3,
    imageSrc: "/assets/images/cake3.jpg",
    imageAlt: "Red Velvet Cake",
    title: "Red Velvet",
    price: "30.00",
    description: "A classic red velvet cake with cream cheese frosting.",
    badgeLabel: "Limited Edition",
  },
  {
    id: 4,
    imageSrc: "/assets/images/cake4.jpg",
    imageAlt: "Strawberry Cake",
    title: "Strawberry Surprise",
    price: "22.00",
    description: "Fresh strawberries with whipped cream on a sponge cake.",
  },
  {
    id: 5,
    imageSrc: "/assets/images/cake1.jpg",
    imageAlt: "Lemon Cake",
    title: "Lemon Zest",
    price: "18.00",
    description: "Tangy lemon cake with a zesty lemon glaze.",
  },
  {
    id: 6,
    imageSrc: "/assets/images/cake2.jpg",
    imageAlt: "Carrot Cake",
    title: "Carrot Bliss",
    price: "28.00",
    description: "Moist carrot cake with creamy vanilla frosting.",
  },
  {
    id: 7,
    imageSrc: "/assets/images/cake3.jpg",
    imageAlt: "Coffee Cake",
    title: "Coffee Crumble",
    price: "24.00",
    description: "A rich coffee-flavored cake with a crunchy crumble topping.",
  },
  {
    id: 8,
    imageSrc: "/assets/images/cake4.jpg",
    imageAlt: "Coconut Cake",
    title: "Coconut Paradise",
    price: "26.00",
    description: "Fluffy coconut cake with a creamy coconut frosting.",
  },
  {
    id: 9,
    imageSrc: "/assets/images/cake1.jpg",
    imageAlt: "Pineapple Cake",
    title: "Pineapple Punch",
    price: "23.00",
    description: "A tropical pineapple cake with layers of pineapple filling.",
  },
  {
    id: 10,
    imageSrc: "/assets/images/cake2.jpg",
    imageAlt: "Mango Cake",
    title: "Mango Mania",
    price: "27.00",
    description: "Sweet mango cake with a light and fluffy texture.",
    badgeLabel: "New Arrival",
  },
  {
    id: 11,
    imageSrc: "/assets/images/cake3.jpg",
    imageAlt: "Banana Cake",
    title: "Banana Bonanza",
    price: "22.00",
    description: "Moist banana cake with a caramel drizzle.",
  },
  {
    id: 12,
    imageSrc: "/assets/images/cake4.jpg",
    imageAlt: "Blueberry Cake",
    title: "Blueberry Bliss",
    price: "25.00",
    description: "A cake bursting with fresh blueberries and cream.",
  },
  {
    id: 13,
    imageSrc: "/assets/images/cake1.jpg",
    imageAlt: "Apple Cake",
    title: "Apple Cinnamon",
    price: "24.00",
    description: "Warm apple cake with cinnamon and brown sugar topping.",
  },
  {
    id: 14,
    imageSrc: "/assets/images/cake2.jpg",
    imageAlt: "Peach Cake",
    title: "Peach Perfection",
    price: "26.00",
    description:
      "Sweet and juicy peach cake with a smooth cream cheese frosting.",
  },
  {
    id: 15,
    imageSrc: "/assets/images/cake3.jpg",
    imageAlt: "Raspberry Cake",
    title: "Raspberry Ripple",
    price: "23.00",
    description: "Tangy raspberry cake with a swirl of raspberry puree.",
    badgeLabel: "Seasonal",
  },
  {
    id: 16,
    imageSrc: "/assets/images/cake4.jpg",
    imageAlt: "Mint Chocolate Cake",
    title: "Mint Choc Chip",
    price: "28.00",
    description:
      "Chocolate cake with a refreshing mint chocolate chip frosting.",
  },
  {
    id: 17,
    imageSrc: "/assets/images/cake1.jpg",
    imageAlt: "Cinnamon Cake",
    title: "Cinnamon Spice",
    price: "22.00",
    description: "A warm cinnamon cake with a hint of nutmeg and spice.",
  },
  {
    id: 18,
    imageSrc: "/assets/images/cake2.jpg",
    imageAlt: "Pumpkin Cake",
    title: "Pumpkin Patch",
    price: "25.00",
    description: "Seasonal pumpkin cake with a spiced cream cheese frosting.",
  },
  {
    id: 19,
    imageSrc: "/assets/images/cake3.jpg",
    imageAlt: "Black Forest Cake",
    title: "Black Forest",
    price: "30.00",
    description: "A decadent black forest cake with cherries and chocolate.",
    badgeLabel: "Customer Favorite",
  },
  {
    id: 20,
    imageSrc: "/assets/images/cake4.jpg",
    imageAlt: "Orange Cake",
    title: "Orange Sunshine",
    price: "21.00",
    description: "A bright and zesty orange cake with a sweet citrus glaze.",
  },
];

export default dummyCakes;
